void setup_application(void);
void run_application(void);
void show_screen_savers(void);
void show_game(u8 state);
void show_puzzle(void);
bool is_submenu_valid(void);
void set_frame_rainbow(void);
void set_frame_audio(void);
void set_frame_blink(void);
void show_counter(void);
void set_frame_space_bits(void);
void set_frame_morse(void);